# -*- coding: utf-8 -*-
"""兼容垫片：主题令牌已迁移至 ui_fluent.py (Windows 11 Fluent 设计系统)。

本模块仅 re-export 全部令牌与工具函数, 使历史 `from .ui_morandi import ...`
继续可用; 新代码请直接 import ui_fluent。计划在引用全部迁移后移除本垫片。
"""
from .ui_fluent import (  # noqa: F401
    # 字体/字号/字重
    FONT_STACK, FONT_TERMINAL,
    SIZE_TITLE, SIZE_SUBTITLE, SIZE_LABEL, SIZE_BODY, SIZE_SMALL, SIZE_TINY,
    WEIGHT_TITLE, WEIGHT_SUBTITLE, WEIGHT_BODY, WEIGHT_EMPHASIS,
    txt,
    # 语义色 (MORANDI_* 为历史命名, 值已映射 Fluent 色板)
    MORANDI_PRIMARY, MORANDI_SECONDARY, MORANDI_TERTIARY, MORANDI_ACCENT,
    MORANDI_SUCCESS, MORANDI_ERROR, MORANDI_WARNING, MORANDI_INFO,
    MORANDI_RUNNING, MORANDI_STOPPED, MORANDI_PENDING,
    MORANDI_SIDEBAR_BG, MORANDI_SIDEBAR_HOVER, MORANDI_SIDEBAR_ACTIVE,
    MORANDI_BACKGROUND, MORANDI_SURFACE, MORANDI_SURFACE_CONTAINER,
    MORANDI_SURFACE_CONTAINER_HIGH, MORANDI_SURFACE_CONTAINER_HIGHEST,
    MORANDI_ON_PRIMARY, MORANDI_ON_SECONDARY, MORANDI_ON_SURFACE,
    MORANDI_ON_SURFACE_VARIANT, MORANDI_OUTLINE, MORANDI_OUTLINE_VARIANT,
    MORANDI_MAUVE, MORANDI_GOLD, MORANDI_TEAL, MORANDI_CLAY, MORANDI_LILAC,
    MORANDI_TERMINAL_BG, LOG_COLOR_INFO, LOG_COLOR_ERROR, LOG_COLOR_WARN,
    LOG_COLOR_DEBUG,
    # 主题与工具
    make_morandi_theme, make_morandi_dark_theme, make_morandi_card,
    get_font_stack, get_terminal_font, get_terminal_bg,
    open_dialog, close_dialog,
)
